### ISSUE TITLE
onFloorChangeError 

### ISSUE THREAD

**Issue by MGasztold** [Mapwize/mapwize-ui-android#43]
Hello,

I have an issue of this part of mapwize-ui-android code being called:

```
@Override
    public void showErrorMessage(String message) {
        new Handler(Looper.getMainLooper()).post(() -> {
            Toast.makeText(getContext(), getContext().getResources().getString(R.string.mapwize_display_content_error), Toast.LENGTH_LONG).show();
        });
    }
```

of `MapwizeUIView.java`.

I debugged a bit and found out this is called from

```
@Override
    public void onFloorChangeError(@Nullable Floor floor, @NonNull Throwable error) {
        fragment.showActiveFloor(null);
        fragment.showErrorMessage("Cannot load this floor");
    }
```
of `MapPrezenter.java`.

I would like to understand why it is like that. It seems it is caused by indoorlocation object being dispatched to mapwize.

**Comment by m3ftah** [comment]
Hello,

When `onFloorChangeError` method is called, this means the Mapwize sdk could not change the floor, this can be due to : 

- Internet connection loss.
- You don't have access to that floor.
- The floor does not exist.

Please check all if these potential error sources, if the `onFloorChangeError` method is still called, please share with us more information about your current map information and your app implementation.
You can privately share with us all the data relating to this issue at : support@mapwize.io.

**Comment by MGasztold** [comment]
@m3ftah Thank you. I have sent you more detailed e-mail on support@mapwize.io.

**Comment by m3ftah** [comment]
Hi,

I am closing this issue because it has been inactive for few months.

Please reopen if you still encounter this issue.

Thanks.
